### ISSUE TITLE
[4주차] 컴퓨터 구조 

### ISSUE THREAD

**Issue by c0olcode** [Kernel360-cell1/cs-study#16]
- CPU에서 명령어를 실행하는 순서를 설명하세요
: 명령어 사이클, 명령어 파이프라이닝 언급

**Comment by hodadako** [comment]
* 0.1 + 1.1 이 1.2이 아닌 이유에 대해서 설명해주세요.
* 캐시 미스에 대해서 설명해 주세요.
* 명령어 파이프라이닝은 왜 존재할까요? 어떤 단점이 있을까요?
* 사진, 영상과 같은 기록물을 저장한다고 하면 어디에 저장하는게 좋을까요?
* 멀티스레드와 멀티코어에 대해서 설명해주세요!

**Comment by GBGreenBravo** [comment]
- RAM과 ROM에 대해 설명해 주세요.
- 메모리, 디스크, 캐시, 레지스터에 대해 접근 속도가 빠른 순으로 나열해 주세요.
- CPU의 기본 구성 요소 3가지에 대해 설명해 주세요
