### ISSUE TITLE
[5주차] 운영체제_1

### ISSUE THREAD

**Issue by GBGreenBravo** [Kernel360-cell1/cs-study#17]
- 프로세스와 스레드의 차이에 대해 설명해 주세요.
- 사용자 수준 스레드와 커널 수준 스레드 차이에는 무엇이 있을까요? 
  - 사용자 수준 스레드
    - 장점 : context switching이 없어서 커널 스레드보다 오버헤드가 적음 (스레드 전환 시 커널 스케줄러 호출할 필요가 없기 때문)
    - 단점 : 프로세스 내의 한 스레드가 커널로 진입하는 순간, 나머지 스레드들도 전부 정지됨 (커널이 스레드의 존재를 알지 못하기 때문에)
  - 커널 수준 스레드
    - 장점 : 사용자 수준 스레드보다 효율적임. 커널 스레드를 쓰면 멀티프로세서를 활용할 수 있기 때문이다. 사용자 스레드는 CPU가 아무리 많아도 커널 모드의 스케줄이 되지 않으므로, 각 CPU에 효율적으로 스레드 배당할 수가 없음
    - 단점 : context switching이 발생함. 이 과정에서 프로세서 모드가 사용자 모드와 커널 모드 사이를 움직이기 때문에 많이 돌아다닐 수록 성능이 떨어지게 된다.
- 선점형 스케쥴링과 비선점형 스케쥴링의 장단점을 비교해 주세요.
- 프로그램의 종류에 대해서 설명해 주세요. 
  
  ![image](https://github.com/Kernel360-cell1/cs-study/assets/147565215/4227768a-534b-4f5a-9315-f8f54a8cc3dc)

  - [포스팅 참조](https://suhyunsim.github.io/2023-03-14/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EB%A9%B4%EC%A0%91%EC%A7%88%EB%AC%B8)
- 컨텍스트 스위칭(Context Switching)에 대해 설명해 주세요.

**Comment by c0olcode** [comment]
- PCB가 무엇이고, 어떤 정보들을 가지고 있는지 설명해 주세요. 
- 메모리의 사용자 영역에 대해 설명해 주세요.
- 힙 영역은 낮은 주소에서 높은 주소로, 스택 영역은 높은 주소에서 낮은 주소로 주소를 할당합니다. 왜 그렇게 할당하는지 다른 영역과 비교해서 설명해 주세요. 
- 프로세스 상태에는 어떤 것들이 있는지 설명해 주세요.

**Comment by hodadako** [comment]
* 멀티 스레드 프로그램을 구현할 때 고려해야할 점으로는 어떤 것들이 있을까요? (Thread-safe)
[데브시스터즈 서버 직군 코딩 테스트](https://tech.devsisters.com/posts/server-position-coding-test)
* 아사 현상에 대해서 설명해 주세요. 어떤 방법으로 해결할 수 있을까요?
* 멀티 프로세스 구조로 되어있는 시스템에서 프로세스 간 통신은 어떤 방식으로 이루어지나요? (강의에 없음)
* 자바에서 어떤 방법을 통해 Thread-safe 한 설계를 할 수 있을까요?
