### ISSUE TITLE
[6주차] 운영체제_2

### ISSUE THREAD

**Issue by GBGreenBravo** [Kernel360-cell1/cs-study#19]
- 뮤텍스와 세마포어의 차이점을 설명해 보세요.
- 자바에서 스레드 안전을 구현하는 방법에 대해 설명해 주세요.
- 가상 메모리란 무엇이고 가상 메모리가 필요한 이유를 설명해 주세요.
- 페이징에서 프로세스가 페이지 번호를 찾아내는 과정을 설명해 주세요.
- 스레싱(threshing)이란 무엇인가요?

**Comment by hodadako** [comment]
* 운영체제가 임계 구역 문제를 해결하는 원칙 3가지를 설명해 주세요.
* 교착 상태(데드락) 발생 조건에 대해서 설명해 주세요.
* 철학자 문제에 대해서 설명해 주세요.
* 최적 페이지 교체 알고리즘에 대해서 설명해주세요? 왜 생겨났을까요?
* 바쁜 대기에 대해 설명해주세요.

**Comment by c0olcode** [comment]
- hikariCP의 pool size가 3이고 한 트랜잭션 내 필요한 커넥션 수가 4일때 발생하는 문제를 무엇이라 하나요? 그리고 해결 방법은 어떤 것이 있을까요?
https://techblog.woowahan.com/2664/
- 스와핑 이란 무엇인가요?
: 프로세스를 보조기억장치의 일부 영역으로 쫓아내고 당장 필요한 프로세스를 적재하는 메모리 관리 기법
