### ISSUE TITLE
[7주차] 데이터 베이스_질문언제올릴거에요?질문언제올릴거에요?질문언제올릴거에요?질문언제올릴거에요?질문언제올릴거에요?질문언제올릴거에요?질문언제올릴거에요?

### ISSUE THREAD

**Issue by hodadako** [Kernel360-cell1/cs-study#21]
* 트랜잭션 격리 레벨에 대해서 설명해 주세요.
  * A와 B가 동시에 같은 데이터에 읽고 쓰려고 합니다. A는 동일한 데이터를 조회하려고 하고 B는 같은 데이터에 쓰기 작업을 진행한다고 하면 어떤 문제가 생길 수 있을까요?
  * 이번엔 서로 같은 데이터에 쓰기 작업을 진행하고자 합니다. 누구의 데이터 쓰기 작업이 우선되어야 할까요? 트랜잭션 격리는 어떤 식으로 이루어져야 할까요?
* 외부 JOIN에는 어떤 것들이 있고 각각은 어떤 식으로 결과를 보여주는지 설명해 주세요.
* 데이터베이스를 사용하는 이유가 뭐라고 생각하시나요?
* 인덱스는 해시 테이블과 B +- 트리 (B 트리)로 구성할 수 있는데 각각의 장단점을 설명해 주세요.

**Comment by c0olcode** [comment]
태그가 무서워요

**Comment by GBGreenBravo** [comment]
- SELECT 쿼리에서 아래 쿼리 명령어들의 수행 순서를 나열해 주세요.
  - SELECT / WHERE / ORDER BY / GROUP BY / ON / LIMIT / DISTINCT / FROM / JOIN / HAVING
- 데이터 무결성의 종류에 대해 아는 대로 설명해 주세요.
- 제 1, 2, 3 정규형에 대한 각각의 예시를 알려주세요.
- (분산 데이터베이스 시스템의 한 이론인) CAP 이론에 대해 설명해 주세요.
- 데이터베이스 뷰에 대해서 설명해 주세요.

**Comment by c0olcode** [comment]
- 정규화/비정규화의 장단점에 대해 설명하세요.
 

- 데이터베이스 트랜잭션의 ACID 특성에 대해 설명하세요.

- 트랜잭션의 ACID 특성을 지키기 위한 방법에는 무엇이 있을까요?


- SQL에서의 AGGREGATE 함수(SUM, AVG, COUNT, MAX, MIN)와 DDD 아키텍처에서의 aggregate에 대해 설명하시오
